
["Î©"]
type="Element{:Tri3}"
"ğ“’".tag="Î©"
"ğ“–".type="TriGI3"
"ğ“–"."ğ­"="âˆ‡ğ­"

["Î“áµ—"]
type="Element{:Seg2}"
"ğ“’".tag="Î“áµ—"
"ğ“–".type="SegGI2"
"ğ“–"."ğ­"="ğ­"

["Î“áµ"]
type="Element{:Seg2}"
"ğ“’".tag="Î“áµ"
"ğ“–".type="SegGI2"
"ğ“–"."ğ­"="ğ­"

["Î©Ì„"]
type="Element{:Tri3}"
"ğ“’".tag="Î©"
"ğ“–".type="TriGI6"
"ğ“–"."ğ­"="âˆ‡ğ­"